name: EVQA
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - tensorflow
    - tensorflow_hub
    - imageio==2.35.1
    - matplotlib==3.7.5
    - ipython==8.12.3
    - oss2==2.19.1
    - decord==0.6.0
    - ruamel.yaml==0.18.11
    - timm==1.0.15
    - scipy==1.10.1
    - opencv-python==4.1.2.30
    - einops==0.8.1
    - transformers==4.25.1
    - torchmetrics==0.6.0
    - ftfy==6.2.3
    - huggingface_hub==0.25.0
    - diffusers==0.10.0
